---
version: "3.3"
services:
  db:
    image: dockerdeepak/workshop:pgdb_v1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: db
  developer:
    image: viveksisodia1108/gogingorm:v1.0
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: workshop
      DB_SCHEMA: transaction
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - 3000:3000
    container_name: goapp
