version: "3.3"

services:
  developer:
    build: .
    env_file:
      - .env
    image: dockerdeepak/workshop:jdk17_mvn_go
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9080:9080
      - 7777:7777
      - 8080:8080
      - 5005:5005
    command: go run cmd/main.go -b 0.0.0.0
    container_name: myapp
  db:
    image: dockerdeepak/workshop:pgdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    container_name: pgdb  
